version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "127.0.0.1:8000:8000"
    tty: true
    volumes:
      - .:/app:ro
    environment:
      auth_token: "my_token"
      debug: 1
